trainer: nae 
logger: nae
model:
    arch: nae 
    encoder: 
        arch: conv64 
        nh: 32 
        out_activation: linear 
        activation: relu
        use_bn: false 
        num_groups: 8
    decoder:
        arch: deconv64 
        nh: 32
        use_bn: false 
        num_groups: 8
        out_activation: sigmoid
    nae:
        spherical: True
        gamma: 1
        delta: Null
        deterministic: True
        sampling: on_manifold

        z_step: 20
        z_stepsize: 1 
        z_noise_std: 0.02
        z_noise_anneal: Null 
        z_clip_langevin_grad: Null
        x_step: 40
        x_stepsize: 20
        x_noise_std: 0.02
        x_noise_anneal: 1
        x_clip_langevin_grad: 0.01

        buffer_size: 10000
        replay_ratio: 0.95
        replay: True
        
        x_bound:
            - 0
            - 1
        z_bound: Null
        l2_norm_reg: Null
        l2_norm_reg_en: Null
        sigma: 0.001
        temperature: 1.
        temperature_trainable: False

    x_dim: 3
    z_dim: 64
data:
    indist_train:
        dataset: CelebA_OOD 
        path: datasets
        batch_size: 128
        n_workers: 8
        split: training 
        shuffle: True
        size: 64
        augmentations:
          hflip:
            p: 0.5
        dequant:
          UniformDequantize: {}
    indist_val:
        dataset: CelebA_OOD 
        path: datasets
        batch_size: 128
        n_workers: 8
        split: validation 
        size: 64
    ood_val:
        dataset: CelebA_OOD 
        channel: 3
        path: datasets
        batch_size: 128
        split: validation
        n_workers: 8
        size: 64
        dequant:
          togray: {}
    ood_target:
        dataset: ConstantGray_OOD 
        size: 64
        path: datasets
        batch_size: 128
        n_workers: 8
        split: validation
training:
  # load_ae: /opt/home3/swyoon/energy-based-autoencoder/src/results/celeba_ood_nae/big/run/model_best.pkl
    ae_epoch: 30
    nae_epoch: 15
    lr_schedule: null
        # name: on_plateau
        # factor: 0.5
        # patience: 3
        # min_lr: 1.0e-4
    resume: null
        # file: /a/b/c.pkl
        # optimizer: False 
    print_interval: 100
    val_interval: 200
    save_interval: 2000
    ae_lr: 1.0e-4
    nae_lr: 1.0e-5
    temperature_lr: 1.0e-3
    fix_D: false 
